name: Lint

on:
  pull_request:
    branches: [ "**" ]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 23.7.0
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'
          cache: 'npm'

      - name: Upgrade to npm 11.1.0
        run: npm install -g npm@11.1.0

      - name: Confirm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and output JSON report
        run: |
          npm run lint -- --format json --output-file eslint_report.json || echo "ESLint completed with warnings/errors"
      
      - name: Print ESLint report for debugging
        run: cat eslint_report.json

      - name: Annotate ESLint warnings
        uses: ataylorme/eslint-annotate-action@v2
        with:
          report-json: eslint_report.json
      